# Generated by Django 4.1.1 on 2022-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic Stadium', max_length=32)),
                ('address', models.CharField(default='Default Stadium', max_length=64)),
                ('phone', models.CharField(blank=True, default='1234567890', max_length=10, null=True)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
