# Generated by Django 4.1.1 on 2022-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=64)),
                ('trainer', models.CharField(default='Francisco Rodriguez', max_length=64)),
                ('players_quantity', models.IntegerField()),
            ],
        ),
    ]
