# Generated by Django 4.1.1 on 2022-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.CharField(default='No trainer', max_length=64),
        ),
    ]
