# Generated by Django 4.1.1 on 2022-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
