# Generated by Django 4.1.1 on 2022-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_number_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Generic Nationality', max_length=32),
        ),
    ]
