# Generated by Django 4.1.1 on 2022-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_age_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
