# Generated by Django 4.1.1 on 2022-09-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isActive',
        ),
    ]
