# Generated by Django 4.1.1 on 2022-09-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_shirt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='shirt_number',
        ),
    ]
