# Generated by Django 4.1.1 on 2022-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player_shirt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
