# Generated by Django 4.1.1 on 2022-09-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_trainer'),
        ('players', '0009_player_shirt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
    ]
