# Generated by Django 4.1.1 on 2022-09-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
