# Generated by Django 4.1.1 on 2022-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
